---
    - name: Create the slurm.conf file
      template: dest={{ SLURM_CONF }} src=slurm.conf.j2
      notify: reload slurm

    # start SLURM daemon
    - service: name={{SLURM_SERVICE}} state=started
    
    - name: Ensure slurmd is not running on controller node
      shell: pgrep slurmd && killall slurmd
      ignore_errors: yes
